server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  absolute_redirect off;

  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;

  location ~ ^/ny/?$ {
    return 301 /new-york/;
  }

  location ~ ^/sf/?$ {
    return 301 /san-francisco/;
  }

  location ~ ^/discord/?$ {
    return 301 https://discord.gg/queerjs;
  }

  location = /sw.js {
    add_header Cache-Control "public, max-age=0, must-revalidate";
  }

  location /page-data/ {
    add_header Cache-Control "public, max-age=0, must-revalidate";
  }

  location /static/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location ~ "[.-][0-9a-f]{16,}\.(js|css)$" {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  location / {
    add_header Cache-Control "public, max-age=0, must-revalidate";
    try_files $uri $uri/index.html $uri/ =404;
  }

  error_page 404 /404.html;
}
